### ISSUE TITLE
Privatize the repository

### ISSUE THREAD

**Issue by davidrunger** [appacademy/sqlzoo#11]
I assume that we want this repository to be private like all the rest? @rglassett , do you have the powers to do this?

**Comment by rglassett** [comment]
The other project repos (AR Lite, PollsApp, etc) are public. Should this
one not be?

**Comment by davidrunger** [comment]
My bad. That'll teach me to infer patterns from small sample sizes! I saw a bunch of private repos on my screen and concluded that private is the standard for AppAcademt, but on a second inspection I see that indeed we have many public repos as well. No reason that this repo can't be among them!
